codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        threshold: 1%
        only_pulls: true
    patch:
      default:
        threshold: 1%
        only_pulls: true
