checks:
    php:
        code_rating: true
build:
    dependencies:
        override:
            - command: 'composer install --ignore-platform-reqs --no-interaction'
    nodes:
        analysis:
            environment:
                php:
                    version: 7.1
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
            project_setup:
                override: true
            tests:
                override:
                    - command: ./vendor/bin/phpstan analyse --ansi --memory-limit 256M --error-format=checkstyle | sed '/^\s*$/d' > phpstan-checkstyle.xml
                      analysis:
                          file: phpstan-checkstyle.xml
                          format: 'general-checkstyle'

tools:
  php_code_coverage: true

build_failure_conditions:
    - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection
